---
- name: install apache
  hosts: webservers

  tasks:
    - import_tasks: webserver_tasks.yml

  post_tasks:
    - name: debug author
      debug:
        msg: created by {{ author | default('lennie') }}
        verbosity: 1

    - name: check http access
      delegate_to: "{{ item }}"
      uri:
        url: "http://{{ ansible_hostname }}:8080"
      loop: "{{ groups['dbservers'] }}"

  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
