---
- name: Users
  hosts: all

  tasks:
    - name: Create Users 
      user:
        name: "{{ item.name }}"
        uid: "{{ item.uid | default(omit) }}"
        groups: "{{ item.groups | default(omit) }}"
        state: "{{ item.state | default('present') }}"
      loop: "{{ users }}"
      register: users_result
      tags:
        - usermgmt
    - name: debug author
      debug:
        msg: created by {{ author }}
